runtime: python39
instance_class: F2
env_variables:
  GOOGLE_SHEET_ID: "xxxxxxxxxxxxxxxxxx"
  GSHEET_WORKSHEET_NAME: "TRANSCRIPT FINAL"
  VIDEOASK_GOOGLE_SHEET_ID: "xxxxxxxxxxxxxxxxxx"
  VIDEOASK_GSHEET_WORKSHEET_NAME: "TRANSCRIPT FINAL"

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  script: auto
